name: sf_jrw
description: "JRW Spice Factory Mobile Application (Flutter)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # utils
  dio: ^5.4.0
  uuid: ^4.2.1
  intl: ^0.19.0
  image: ^4.1.4
  jiffy: ^6.2.1
  fpdart: ^1.1.0
  pinput: ^4.0.0
  shimmer: ^3.0.0
  encrypt: ^5.0.3
  decimal: ^3.0.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  carbon_icons: ^0.0.1+2
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  responsive_builder: ^0.7.0
  flutter_form_builder: ^9.1.1
  cached_network_image: ^3.3.0
  modal_progress_hud_nsn: ^0.5.1
  form_builder_validators: ^10.0.1
  mask_text_input_formatter: ^2.7.0

  # framework
  dartz: ^0.10.1
  get_it: ^7.6.4
  stacked: ^3.4.1+1
  flutter_hooks: ^0.20.3
  graphql: ^5.2.0-beta.6
  stacked_services: ^1.3.0
  graphql_flutter: ^5.2.0-beta.7

  # hardware
  app_settings: ^5.1.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  client_information: ^2.1.4
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  logger: ^1.4.0
  mockito: ^5.4.3
  analyzer: ^6.4.1
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  stacked_generator: ^1.5.1
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.4.1
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true